Traceback (most recent call last):
  File "c:\users\plarson\anaconda3\envs\wintest\lib\site-packages\nbclient\client.py", line 627, in _async_poll_for_reply
    msg = await ensure_async(self.kc.shell_channel.get_msg(timeout=new_timeout))
  File "c:\users\plarson\anaconda3\envs\wintest\lib\site-packages\nbclient\util.py", line 89, in ensure_async
    result = await obj
  File "c:\users\plarson\anaconda3\envs\wintest\lib\site-packages\jupyter_client\channels.py", line 230, in get_msg
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\plarson\anaconda3\envs\wintest\lib\site-packages\jupyter_cache\executors\utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "c:\users\plarson\anaconda3\envs\wintest\lib\site-packages\nbclient\client.py", line 1117, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "c:\users\plarson\anaconda3\envs\wintest\lib\site-packages\nbclient\util.py", line 78, in wrapped
    return just_run(coro(*args, **kwargs))
  File "c:\users\plarson\anaconda3\envs\wintest\lib\site-packages\nbclient\util.py", line 57, in just_run
    return loop.run_until_complete(coro)
  File "c:\users\plarson\anaconda3\envs\wintest\lib\asyncio\base_events.py", line 587, in run_until_complete
    return future.result()
  File "c:\users\plarson\anaconda3\envs\wintest\lib\site-packages\nbclient\client.py", line 559, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "c:\users\plarson\anaconda3\envs\wintest\lib\site-packages\nbclient\client.py", line 846, in async_execute_cell
    exec_reply = await self.task_poll_for_reply
  File "c:\users\plarson\anaconda3\envs\wintest\lib\site-packages\nbclient\client.py", line 651, in _async_poll_for_reply
    await self._async_handle_timeout(timeout, cell)
  File "c:\users\plarson\anaconda3\envs\wintest\lib\site-packages\nbclient\client.py", line 702, in _async_handle_timeout
    "Cell execution timed out", timeout, cell
nbclient.exceptions.CellTimeoutError: A cell timed out while it was being executed, after 30 seconds.
The message was: Cell execution timed out.
Here is a preview of the cell contents:
-------------------
['% contrast_phantom', '', '', 'Nphan = 3;', '% phantom parameters']
...
['imagesc(abs(m)), colormap(gray), axis equal tight', "title(['TE = ' int2str(TE) ', TR = ' int2str(TR)])", '', 'end', 'end']
-------------------

